server:
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/expensetracker
    username: root
    password: farid@1510

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
